import type { Metadata } from "next";
import TOP from "@/components/navbar";
import "./globals.css";
import { Poppins } from 'next/font/google'
const poppins = Poppins({ subsets: ['latin'], weight:['400', '700']})



export const metadata: Metadata = {
  title: "Test-valley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={poppins.className}>
     
          <TOP/>
              <main className="relative ">
              {children}
              </main>
      </body>
      
    </html>
  );
}
